---
steps:

# Build echo images.

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: echo-pull
    waitFor: ['-']
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/shared/nginx:echo || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [echo-pull]
    id: echo-build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shared/nginx:echo', '--cache-from', 'gcr.io/$PROJECT_ID/shared/nginx:echo', '.']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [echo-build]
    entrypoint: 'bash'
    args: ['-c', 'docker tag gcr.io/$PROJECT_ID/shared/nginx:echo "gcr.io/$PROJECT_ID/shared/nginx:echo-$(date +%Y%m%d)"']

# Build FPM images.

  - name: 'gcr.io/cloud-builders/docker'
    id: fpm-pull
    waitFor: ['-']
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/shared/nginx:fpm || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [fpm-pull]
    id: fpm-build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shared/nginx:fpm', '--cache-from', 'gcr.io/$PROJECT_ID/shared/nginx:fpm', '.']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [fpm-build]
    entrypoint: 'bash'
    args: ['-c', 'docker tag gcr.io/$PROJECT_ID/shared/nginx:fpm "gcr.io/$PROJECT_ID/shared/nginx:fpm-$(date +%Y%m%d)"']

images:
  - 'gcr.io/$PROJECT_ID/shared/nginx'

