---
steps:

# Build echo images.

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    id: echo-pull
    waitFor: ['-']
    args: ['-c', 'docker pull $_DOCKER_HUB_REPO/nginx:echo || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [echo-pull]
    id: echo-build
    args: ['build', '-t', '$_DOCKER_HUB_REPO/nginx:echo', '--cache-from', '$_DOCKER_HUB_REPO/nginx:echo', '-f', 'echo/Dockerfile', 'echo']

# Build FPM images.

  - name: 'gcr.io/cloud-builders/docker'
    id: fpm-pull
    waitFor: ['-']
    entrypoint: 'bash'
    args: ['-c', 'docker pull $_DOCKER_HUB_REPO/nginx:fpm || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [fpm-pull]
    id: fpm-build
    args: ['build', '-t', '$_DOCKER_HUB_REPO/nginx:fpm', '--cache-from', '$_DOCKER_HUB_REPO/nginx:fpm', '-f', 'fpm/Dockerfile', 'fpm']

# Log in to Docker Hub.

  - name: 'gcr.io/cloud-builders/gcloud'
    id: decrypt-hub-username
    waitFor: ['-']
    args:
      - 'kms'
      - 'decrypt'
      - '--location=global'
      - '--keyring=docker'
      - '--key=hub'
      - '--ciphertext-file=.cloudbuild/docker-hub-username.enc'
      - '--plaintext-file=docker-hub-username.txt'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: decrypt-hub-password
    waitFor: ['-']
    args:
      - 'kms'
      - 'decrypt'
      - '--location=global'
      - '--keyring=docker'
      - '--key=hub'
      - '--ciphertext-file=.cloudbuild/docker-hub-password.enc'
      - '--plaintext-file=docker-hub-password.txt'

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: [decrypt-hub-username, decrypt-hub-password]
    entrypoint: 'bash'
    args: ['-c', 'cat docker-hub-password.txt | docker login --username=$$(cat docker-hub-username.txt) --password-stdin']

images:
  - 'gcr.io/$PROJECT_ID/shared/nginx'

