aliases:
  steps: &steps
    - checkout
    - setup_remote_docker
    - run: docker pull "${DOCKER_HUB_REPO}/nginx:${VERSION}" || true
    - run: docker build -t "${DOCKER_HUB_REPO}/nginx:${VERSION}" --cache-from="${DOCKER_HUB_REPO}/nginx:${VERSION}" --build-arg SRC_VERSION_TAG=${SRC_VERSION_TAG} .
    - run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - run: docker push "${DOCKER_HUB_REPO}/nginx:${VERSION}"

version: 2
jobs:
  build-1.15:
    docker:
      - image: circleci/debian:stretch
    environment:
      VERSION: "1.15"
      SRC_VERSION_TAG: "1.15.9-alpine"
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - build-1.15:
          context: docker-hub
